### ISSUE TITLE
Fatal/FatalIf messages not shown in Concourse UI

### ISSUE THREAD

**Issue by mwieczorek** [ArthurHlt/go-concourse-helper#1]
Hi,
I have a question:
https://github.com/ArthurHlt/go-concourse-helper/blob/master/messager.go#L63
```
func (rl *Messager) Fatal(message string) {
	fmt.Fprintln(rl.ResponseWriter, message)
```
it basically writes to stdout, so it's not shown in Concourse UI (at least in v2.6.0 which I use). 

Why it's not to stderr (as other log messages)?

**Comment by ArthurHlt** [comment]
This is actually not really documented how concourse handle error message on concourse, I've simply copied on other resource how they do (e.g.: https://github.com/concourse/semver-resource/blob/master/check/main.go#L50-L53 ) 
Is it on a check resource ?

**Comment by mwieczorek** [comment]
I found it in out resource. I had some problems during testing ca_cert handling. And no error message was in UI when I added only:
```
msg.Fatal("error opening file")
```
https://github.com/orange-cloudfoundry/artifactory-resource/blob/master/out/main.go#L114

So that's why I added:
```
msg.Logln("Could not read file with props from path: %s; %v", c.params.PropsFromFile, err)
```

**Comment by ArthurHlt** [comment]
this should work normally now: e64471d7c7ec3abbe358b00268d4c031194c98bf
